language: python
postgres:
  adapter: postgresql
  database: famille
  username: postgres
python:
    - "2.7"
install: "make install"
before_script:
  - "psql -c 'create database famille;' -U postgres"
script: "make test"

